name: Go Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Publish cod coverage badge
      run: |
        set -x
        total=`go test -coverprofile=coverage.out | grep coverage | grep -Eo '[0-9]+\.[0-9]+'`
        if (( $(echo "$total <= 50" | bc -l) )) ; then
          COLOR=red
        elif (( $(echo "$total > 80" | bc -l) )); then
          COLOR=green
        else
          COLOR=orange
        fi
        curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > badge.svg
        
    - name: Archive code coverage badge
      uses: actions/upload-artifact@v2
      with:
        name: badge.svg
        path: code-coverage-badge.svg
     
